gm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import misc, calculators, searches, lists, details, prints, faq

app_name = 'gm'
urlpatterns = [
    path('', misc.IndexView.as_view(), name='index'),
    path('about/', misc.AboutView.as_view(), name='about'),
    path('ai_generator/', cache_page(0)(misc.generateAI), name='ai_generator'),
    path('ai_generator/<codename>/', misc.generateAI, name='ai_informations'),
    path('ajax/autocomplete.json', misc.AutocompleteView.as_view(), name='autocomplete'),
    path('ajax/theme', misc.SetTheme.as_view(), name='set_theme'),
    
    path('weapon/', lists.WeaponListView.as_view(), name='weapon_list'),
    path('module/', lists.ModuleListView.as_view(), name='module_list'),
    path('effect/', lists.EffectListView.as_view(), name='effect_list'),
    path('overdrive/', lists.OverdriveListView.as_view(), name='overdrive_list'),
    path('enhancement/', lists.EnhancementListView.as_view(), name='enhancement_list'),
    path('armour/', lists.ArmourListView.as_view(), name='armour_list'),
    path('division/', lists.DivisionListView.as_view(), name='division_list'),
    path('arcana/', lists.ArcanaListView.as_view(), name='arcana_list'),
    path('crest/', lists.CrestListView.as_view(), name='crest_list'),
    path('archetype/', lists.ArchetypeListView.as_view(), name='archetype_list'),
    path('great_deed/', lists.GreatDeedListView.as_view(), name='great_deed_list'),
    path('skill/', lists.HeroicSkillListView.as_view(), name='skill_list'),
    path('vehicle/', lists.VehicleListView.as_view(), name='vehicle_list'),
    path('trauma/', lists.TraumaListView.as_view(), name='trauma_list'),
    path('mecha/', lists.MechaArmourListView.as_view(), name='mecha_list'),
    path('npc_capacity/', lists.NonPlayerCharacterCapacityListView.as_view(), name='npc_capacity_list'),
    
    path('weapon/<int:pk>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<int:pk>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<int:pk>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<int:pk>', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<int:pk>', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/<int:pk>', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<int:pk>', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<int:pk>', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<int:pk>', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('skill/<int:pk>', details.HeroicSkillDetailView.as_view(), name='skill_detail'),
    path('vehicle/<int:pk>', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<int:pk>', details.TraumaDetailView.as_view(), name='trauma_detail'),
    
    path('weapon/<slug:slug>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<slug:slug>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<slug:slug>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<slug:slug>', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<slug:slug>', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/classified', details.ArmourClassifiedView.as_view(), name='armour_unknown'),
    path('armour/<slug:slug>', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<slug:slug>', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<slug:slug>', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<slug:slug>', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('skill/<slug:slug>', details.HeroicSkillDetailView.as_view(), name='skill_detail'),
    path('archetype/<slug:slug>', details.ArchetypeDetailView.as_view(), name='archetype_detail'),
    path('crest/<slug:slug>', details.CrestDetailView.as_view(), name='crest_detail'),
    path('vehicle/<slug:slug>', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<slug:slug>', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('mecha/classified', details.MechaArmourClassifiedView.as_view(), name='mecha_unknown'),
    path('mecha/<slug:slug>', details.MechaArmourDetailView.as_view(), name='mecha_detail'),
    path('npc_capacity/<slug:slug>', details.NonPlayerCharacterCapacityDetailView.as_view(), name='npc_capacity_detail'),
    
    path('longbow_calculator/', calculators.LongbowCalculatorView.as_view(), name='longbow_calculator'),
    
    path('faq/v1', faq.QuestionV1ListView.as_view(), name='faqv1'),
    path('faq/v1.5', faq.QuestionV1Dot5ListView.as_view(), name='faqv1.5'),
    
    path('search/', searches.search, name='search'),
    
    path('print/weapon/', prints.WeaponPrintListView.as_view(), name='print_weapon'),
    path('print/module/', prints.ModulePrintListView.as_view(), name='print_module'),
    path('print/overdrive/', prints.OverdrivePrintListView.as_view(), name='print_overdrive'),
    path('print/enhancement/', prints.EnhancementPrintListView.as_view(), name='print_enhancement'),
    path('print/trauma/', prints.TraumaPrintListView.as_view(), name='print_trauma'),

]

knight_master_overview/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib.auth.decorators import login_required

from .views import account

urlpatterns = [
    path('camelot/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/', include('api.urls')),
    path('accounts/login/', account.JointLoginSignupView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
]

gm_urls = ([
    path('', include('gm.urls')),
], 'gm')


virtualtable_urls = ([
    path('', include('virtualtable.urls')),
], 'virtualtable')

urlpatterns += i18n_patterns(
    path('', include('gm.urls')),
    path('virtualtable/', include('virtualtable.urls')),
    path('users/', include('users.urls')),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

virtualtable/urls.py
from django.urls import include, path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'virtualtable'
urlpatterns = [
    path('create/', cache_page(0)(views.CreateTableView.as_view()), name='vt_create'),
    path('list/', cache_page(0)(views.ListTableView.as_view()), name='vt_list'),
    path('detail/<int:pk>', cache_page(0)(views.DetailTableView.as_view()), name='vt_detail'),
    path('delete/<int:pk>', cache_page(0)(views.DeleteTableView.as_view()), name='vt_delete'),
    path('update/<int:pk>', cache_page(0)(views.UpdateTableView.as_view()), name='vt_update'),
    path('help/', cache_page(0)(views.HelpTableView.as_view()), name='vt_help'),
    
    path('test/', cache_page(0)(views.TestView.as_view()), name='vt_test'),
    
    path('join/<str:invitation_token>/', cache_page(0)(views.PlayerJoinTableView.as_view()), name='join'),
]

virtualtable/models.py
from datetime import timedelta
import json
import logging

from django.db import models
from django.utils import timezone
from martor.models import MartorField
from colorful.fields import RGBColorField
from users.models import CustomUser
from django.utils.translation import gettext_lazy
from django.db.models import Q, Min

from gm.models.character import GreatDeed, Archetype, Armour, Aspect, Crest, Characteristic, MajorArcana, Division
# Create your models here.

logger = logging.getLogger(__name__)

class VirtualTable(models.Model):
    DUR_30MN = '30mn'
    DUR_1H = '1h'
    DUR_6H = '6h'
    DUR_12H = '12h'
    DUR_24H = '24h'
    DUR_ALWAYS = 'always'
    duration_choices = (
        (DUR_30MN, gettext_lazy('30 minutes')),
        (DUR_1H, gettext_lazy('1 heure')),
        (DUR_6H, gettext_lazy('6 heures')),
        (DUR_12H, gettext_lazy('12 heures')),
        (DUR_24H, gettext_lazy('24 heures')),
        (DUR_ALWAYS, gettext_lazy('Toujours')),
    )
    
    name = models.CharField(gettext_lazy('nom'), max_length=64)
    description = models.TextField(blank=True)
    max_character = models.PositiveSmallIntegerField(gettext_lazy('nb. personnage max'))
    game_master = models.ForeignKey(
        CustomUser,
        related_name='managed_tables',
        on_delete=models.CASCADE,
        limit_choices_to={'game_master': True}
    )
    invitation_token = models.CharField(gettext_lazy('clé d\'invitation'), max_length=16, null=True, unique=True, blank=True)
    token_valid_duration = models.CharField(gettext_lazy('accessible pendant'), max_length=6, choices=duration_choices)
    token_creation_date = models.DateTimeField(gettext_lazy('date création token'))
    active_avalon = models.BooleanField(gettext_lazy('activer Avalon'), default=False, blank=True)
    
    def token_has_expired(self):
        if self.invitation_token is None or self.invitation_token == '':
            return True
        
        if self.token_valid_duration == self.DUR_ALWAYS:
            return False
        
        delta = None
        if self.token_valid_duration == self.DUR_30MN:
            delta = timedelta(minutes=30)
        if self.token_valid_duration == self.DUR_1H:
            delta = timedelta(hours=1)
        if self.token_valid_duration == self.DUR_6H:
            delta = timedelta(hours=6)
        if self.token_valid_duration == self.DUR_12H:
            delta = timedelta(hours=12)
        if self.token_valid_duration == self.DUR_24H:
            delta = timedelta(hours=24)
        
        if delta is None:
            return True
        
        return self.token_creation_date + delta < timezone.now()
    
    def get_last_gm_rolls(self):
        """
        Get the last 30 rolls made by the GM.
        """
        return self.gm_rolls.order_by('-datetime').all()[:30]

class VirtualTablePlayer(models.Model):
    EDIT_LVL_PLAYER = 'p'
    EDIT_LVL_ALL = 'a'
    EDIT_LVL_GM = 'g'
    edit_level_choices = (
        (EDIT_LVL_PLAYER, gettext_lazy('joueur')),
        (EDIT_LVL_ALL, gettext_lazy('tous')),
        (EDIT_LVL_GM, gettext_lazy('MJ')),
    )
    
    GEST_ADVANTAGE_BALANCE = 'b'
    GEST_ADVANTAGE_LIGHT = 'l'
    GEST_ADVANTAGE_NONE = 'n'
    gest_advantage_choices = (
        (GEST_ADVANTAGE_BALANCE, gettext_lazy('équilibre')),
        (GEST_ADVANTAGE_LIGHT, gettext_lazy('lumière')),
        (GEST_ADVANTAGE_NONE, gettext_lazy('aucun')),
    )
    
    player = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='virtualtables')
    virtual_table = models.ForeignKey(VirtualTable, on_delete=models.CASCADE, related_name="players")
    name = models.CharField(gettext_lazy('nom personnage'), max_length=256)
    current_armour_points = models.PositiveSmallIntegerField(gettext_lazy("PA actuels"), null=True, blank=True)
    current_energy_points = models.PositiveSmallIntegerField(gettext_lazy("PE actuels"), null=True, blank=True)
    current_force_field = models.PositiveSmallIntegerField(gettext_lazy("CDF actuel"), null=True, blank=True)
    current_aegis = models.PositiveSmallIntegerField(gettext_lazy("Égide actuelle"), null=True, blank=True)
    current_health_points = models.PositiveSmallIntegerField(gettext_lazy("PS actuels"), null=True, blank=True)
    current_hope_points = models.PositiveSmallIntegerField(gettext_lazy("PES actuels"), default=50)
    current_armour_nod = models.PositiveSmallIntegerField(gettext_lazy("nods d'armure actuels"), blank=True, default=3)
    current_energy_nod = models.PositiveSmallIntegerField(gettext_lazy("nods d'énergie actuels"), blank=True, default=3)
    current_health_nod = models.PositiveSmallIntegerField(gettext_lazy("nods de soin actuels"), blank=True, default=3)
    current_grenade_stock = models.PositiveSmallIntegerField(gettext_lazy("grenades actuelles"), blank=True, default=5)
    current_heroism_points = models.PositiveSmallIntegerField(gettext_lazy('points héroïsme actuels'), default=0, blank=True)
    current_flux_points = models.PositiveSmallIntegerField(gettext_lazy("flux actuel"), null=True, blank=True) # only for psion
    current_impregnation_points = models.PositiveSmallIntegerField(gettext_lazy("imprégnation actuelle"), null=True, blank=True) # only for shaman
    current_gp = models.PositiveSmallIntegerField(gettext_lazy('PG actuels'), default=0, blank=True)
    current_xp = models.PositiveSmallIntegerField(gettext_lazy('PX actuels'), default=0, blank=True)
    default_force_field = models.PositiveSmallIntegerField(gettext_lazy("CDF par défaut"), null=True, blank=True)
    default_aegis = models.PositiveSmallIntegerField(gettext_lazy("Égide par défaut"), null=True, blank=True)
    max_armour_points = models.PositiveSmallIntegerField(gettext_lazy("PA max"), null=True, blank=True)
    max_energy_points = models.PositiveSmallIntegerField(gettext_lazy("PE max"), null=True, blank=True)
    max_health_points = models.PositiveSmallIntegerField(gettext_lazy("PS max"), null=True, blank=True)
    max_hope_points = models.PositiveSmallIntegerField(gettext_lazy("PES max"), default=50)
    max_armour_nod = models.PositiveSmallIntegerField(gettext_lazy("nods d'armure max"), blank=True, default=3)
    max_energy_nod = models.PositiveSmallIntegerField(gettext_lazy("nods d'énergie max"), blank=True, default=3)
    max_health_nod = models.PositiveSmallIntegerField(gettext_lazy("nods de soin max"), blank=True, default=3)
    max_grenade_stock = models.PositiveSmallIntegerField(gettext_lazy("grenades max"), blank=True, default=5)
    max_heroism_points = models.PositiveSmallIntegerField(gettext_lazy("points d'héroïsme max"), default=6, blank=True)
    max_flux_points = models.PositiveSmallIntegerField(gettext_lazy("flux max"), null=True, blank=True) # only for psion
    max_impregnation_points = models.PositiveSmallIntegerField(gettext_lazy("imprégnation max"), null=True, blank=True) # only for shaman
    total_gp = models.PositiveSmallIntegerField(gettext_lazy('PG totaux'), default=0, blank=True)
    total_xp = models.PositiveSmallIntegerField(gettext_lazy('PX totaux'), default=0, blank=True)
    impregnation_difficulty = models.SmallIntegerField(gettext_lazy("difficulté d'imprégnation"), help_text=gettext_lazy("Représente la difficulté du test d'imprégnation qui augmente à chaque fois qu'une capacité est utilisée. Remis à 0 entre chaque mission."), null=True, blank=True) # only for shaman
    time_paradox_difficulty = models.SmallIntegerField(gettext_lazy("difficulté de paradoxe temporel"), help_text=gettext_lazy("Représente la difficulté du test d'imprégnation qui augmente à chaque fois qu'une capacité est utilisée. Remis à 0 entre chaque scène."), null=True, blank=True) # only for warlock
    lost_energy_counter = models.SmallIntegerField(gettext_lazy("nombre PE perdus"), help_text=gettext_lazy("Représente les PE perdus sur ce combat et devant être restauré à hauteur de 1D6 par 6 points perdus"), default=0, blank=True)
    lost_hope_counter = models.SmallIntegerField(gettext_lazy("nombre PES perdus"), help_text=gettext_lazy("Représente les PES perdus sur ce combat et devant être restauré à hauteur de 1D6 par 6 points perdus"), default=0, blank=True)
    gest_advantage = models.CharField(gettext_lazy('avantage geste'), max_length=1, choices=gest_advantage_choices, default=GEST_ADVANTAGE_NONE)
    edit_level = models.CharField(gettext_lazy('éditable par'), max_length=1, choices=edit_level_choices, default=EDIT_LVL_PLAYER)
    ignore_health_loss_by_armour = models.BooleanField(gettext_lazy("Ignore la perte de PS via armure"), default=False)
    classes_to_show = models.TextField("classes CSS à afficher", default=".tab-status,.bar-health-points,.bar-armour-points,.bar-energy-points,.bar-hope-points,.counter-force-field,.tab-stock,.bar-health-nods,.bar-armour-nods,.bar-energy-nods,.bar-grenades-stock,.tab-legend,.bar-hero-points,.bar-glory-points,.bar-experience-points", blank=True)
    
    def get_last_rolls(self):
        """
        Get the last 30 rolls made by the character, combined with the GM public ones.
        
        Note: The *:*:-1 notation reverse the array, due to the order_by changing
        the good order to display. (EDIT: not true anymore, changed the order rules)
        """
        return self.rolls.union(VirtualTableRoll.objects.filter(virtual_table_player=None,virtual_table_gm=self.virtual_table,public=True).all()).order_by('-datetime').all()[:30]
        
    def get_last_public_rolls(self):
        """
        Get the last 30 public rolls made by the character, combined with the GM public ones.
        """
        return self.rolls.filter(public=True).union(VirtualTableRoll.objects.filter(virtual_table_player=None,virtual_table_gm=self.virtual_table,public=True).all()).order_by('-datetime').all()[:30]

class VirtualTableRoll(models.Model):
    virtual_table_player = models.ForeignKey(VirtualTablePlayer, on_delete=models.CASCADE, related_name='rolls', blank=True, null=True) # only for player rolls

virtualtable/templates/virtualtable/character_creation.html
{% extends 'virtualtable/base.html' %}

{% load static %}
{% load martortags %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load gm_extras %}

{% block content %}
<form method="post">
    <h1 class="text-center">Création de personnage</h1>
    {% csrf_token %}
    {% crispy form %}
</form>
{% endblock %}

virtualtable/templates/virtualtable/character_value.html
{% load i18n %}
{% load static %}

<div class="{{ global_class }}" data-attr-code="{{ attr_code }}">
	{% spaceless %}
		<div class="d-block d-xl-none text-center">
			<div class="row m-0">
				<div class="col-4 p-0">
					<div>
						<button type="button" class="mr-0 align-top btn btn-link btn-sm manage-player" onclick="virtual_table.sub_value(this);">
							<i class="fas fa-minus-circle"></i>
						</button>
					</div>
				</div>
				<div class="col-4 p-0 max-width-when-compressed">
					<small class="badge badge-pill bg-{{ global_class }}" data-toggle="tooltip" title="{% trans full_label %}">{% trans label %}</small>
				</div>
				<div class="col-4 p-0">
					<div>
						<button type="button" class="btn m-0 align-top btn-link btn-sm manage-player" onclick="virtual_table.add_value(this);">
							<i class="fas fa-plus-circle"></i>
						</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<a href="#" data-toggle="modal" data-target="#updateValues" data-attr-code="{{ attr_code }}" class="badge badge-light badge-label" default-value="{% if default_value is None %}0{% else %}{{ default_value }}{% endif %}">{% if current_value is not None %}{{ current_value }}{% elif default_value is not None %}{{ default_value }}{% else %}0{% endif %}</a>
					<a class="m-0 ml-1 align-middle manage-player button-redo" href="#" onclick="virtual_table.reset_value(this);" role="button"><small><i class="fas fa-redo"></i></small></a>
				</div>
			</div>
		</div>
		<div class="d-xl-block d-none">
			<div class="row m-0 text-center justify-content-between">
				<div class="col-2 p-0">
					<div class="d-inline-block">
						<small class="badge badge-pill bg-{{ global_class }}" data-toggle="tooltip" title="{% trans full_label %}">{% trans label %}</small>
					</div>
				</div>
				<div class="col-2 p-0">
					<button type="button" class="mr-0 align-top btn btn-link btn-sm manage-player" onclick="virtual_table.sub_value(this);"><i class="fas fa-minus-circle"></i></button>
				</div>
				<div class="col-6 align-top stat-value">
					<div>
						<a href="#" data-toggle="modal" data-target="#updateValues" data-attr-code="{{ attr_code }}" class="badge badge-light badge-label" default-value="{% if default_value is None %}0{% else %}{{ default_value }}{% endif %}">{% if current_value is not None %}{{ current_value }}{% elif default_value is not None %}{{ default_value }}{% else %}0{% endif %}</a>
						<a class="m-0 ml-1 align-middle manage-player button-redo" href="#" onclick="virtual_table.reset_value(this);" role="button"><small><i class="fas fa-redo"></i></small></a>
					</div>
				</div>
				<div class="col-2 p-0">
					<button type="button" class="btn m-0 align-top btn-link btn-sm manage-player" onclick="virtual_table.add_value(this);"><i class="fas fa-plus-circle"></i></button>
				</div>
			</div>
		</div>
	{% endspaceless %}
</div>

virtualtable/templates/virtualtable/field.html
{% load crispy_forms_field %}

{% crispy_field field %}
{% include 'bootstrap4/layout/help_text_and_errors.html' %}

virtualtable/templates/virtualtable/test.html
{% extends 'virtualtable/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

virtualtable/templates/virtualtable/vt_delete.html
{% extends "virtualtable/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Suppression d'une table" %} - {% endblock %}

{% block content %}
    {% if not object %}
        <h1 class="mt-3">{% trans "Erreur : Table inaccessible" %}</h1>

        <p>
            {% trans "La table a soit déjà été supprimée, soit vous n'en êtes pas le MJ. Seul le MJ peut supprimer une table virtuelle." %}
        </p>
    {% else %}
        <h1 class="mt-3">{% trans "Suppression définitive" %}</h1>
        <form method="post">{% csrf_token %}
            <div class="alert alert-danger">{% blocktrans with name=object.name %}Attention : la suppression d'une table virtuelle est définitive. Êtes-vous sûr de vouloir supprimer la table virtuelle {{ name }} ainsi que les statistiques associées ? {% endblocktrans %}</div>
            <div class="alert alert-info">{% trans "Notez que si vous confirmez et que des joueurs sont connectés à la table virtuelle, ils seront déconnectés et ramenés à la liste des tables virtuelles." %}</div>
            <a href="{% url 'virtualtable:vt_list' %}" class="btn btn-primary">{% trans "Retour" %}</a>
            <input class="btn btn-danger float-right" type="submit" value="{% trans 'Confirmer' %}">
        </form>
    {% endif %}
{% endblock %}

virtualtable/templates/virtualtable/vt_invitation_expired.html
{% extends 'virtualtable/base.html' %}

{% load i18n %}

{% block title %}{% trans "Invitation expirée" %} - {% endblock %}

{% block content %}
<h1 class="mt-3">{% trans "Erreur : Invitation non valide" %}</h1>

<p>
	{% trans "Impossible de rejoindre cette table. Vérifiez qu'elle existe, qu'il s'agit bien de son lien d'invitation et que l'invitation n'a pas expiré." %}
</p>
{% endblock %}

virtualtable/templates/virtualtable/vt_list.html
{% extends "virtualtable/base.html" %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Liste des tables" %} - {% endblock %}

{% block content %}
<div class="row mt-3">
    <div class="col-12 mb-2">
        <a class="btn btn-primary float-right" href="{% url 'virtualtable:vt_help' %}" target="_blank" title="{% trans "Besoin d'aide ?" %}"><i class="fas fa-question-circle"></i> {% trans "Besoin d'aide ?" %}</a>
    </div>
    <div class="col-12">
        <table class="table table-sm table-striped table-bordered">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="text-center">{% trans "Invitation" %}</th>
                    <th scope="col" class="text-center">{% trans "Nom" %}</th>
                    <th scope="col" class="text-center">{% trans "Description" %}</th>
                    <th scope="col" class="text-center">{% trans "Personnages" %}</th>
                    <th scope="col" class="text-center">
                        {% trans "Actions" %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% if not virtualtable_list %}
                    <tr>
                        <td colspan="5" class="font-italic text-center">{% trans "Aucune table créée ni rejointe. Demandez à un MJ de vous fournir un lien d'invitation afin de pouvoir rejoindre une table" %}{% if user.game_master %}{% trans " ou créez en une directement" %}{% endif %}.</td>
                    </tr>
                {% endif %}
                {% for vt in virtualtable_list %}
                    <tr>
                        <td class="align-middle text-center vt-list-invit">
                            {% if not vt.token_has_expired %}
                                <div class="input-group">
                                    <input final-url="{% url 'virtualtable:join' vt.invitation_token %}" type="text" class="form-control" placeholder="{% trans 'Invitation' %}" aria-label="{% trans 'Invitation' %}" value="{{ vt.invitation_token }}">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" onclick="knightools.copy_invitation(this);">
                                            <i class="fas fa-copy"></i>
                                        </button>
                                    </div>
                                </div>
                            {% else %}
                                {% trans 'Fermée' %}
                            {% endif %}
                        </td>
                        <td class="align-middle text-center">{{ vt.name }}</td>
                        <td class="align-middle">{{ vt.description|safe_markdown }}</td>
                        <td class="align-middle">
                            {% if vt.players.all %}
                                <ul>
                                    {% for character in vt.players.all %}
                                        <li>{{ character.name }}</li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                {% trans "Aucun" %}
                            {% endif %}
                        </td>
                        <td class="align-middle text-center vt-list-manage">
                            <div class="btn-group btn-group" role="group" aria-label="Basic example">
                                <a href="{% url 'virtualtable:vt_detail' vt.id %}">
                                    <button type="button" role="button" class="btn btn-success" title="{% trans 'Voir' %}">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                </a>
                                {% if vt.owned_by_user %}
                                    <a href="{% url 'virtualtable:vt_update' vt.id %}">
                                        <button type="button" role="button" class="btn btn-secondary" title="{% trans 'Gérer' %}">
                                            <i class="fas fa-cog"></i>
                                        </button>
                                    </a>
                                    <a href="{% url 'virtualtable:vt_delete' vt.id %}">
                                        <button type="button" role="button" class="btn btn-danger" title="{% trans 'Supprimer' %}">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            {% if user.game_master %}
            <tfoot>
                <tr>
                    <td colspan="5">
                        <a href="{% url 'virtualtable:vt_create' %}" class="btn btn-success"><i class="fas fa-plus"></i> {% trans "Créer" %}</a>
                    </td>
                </tr>
            </tfoot>
            {% endif %}
        </table>
    </div>
</div>

{% endblock %}