gm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import misc, calculators, searches, lists, details, prints, faq

app_name = 'gm'
urlpatterns = [
    path('', misc.IndexView.as_view(), name='index'),
    path('about/', misc.AboutView.as_view(), name='about'),
    path('ai_generator/', cache_page(0)(misc.generateAI), name='ai_generator'),
    path('ai_generator/<codename>/', misc.generateAI, name='ai_informations'),
    path('ajax/autocomplete.json', misc.AutocompleteView.as_view(), name='autocomplete'),
    path('ajax/theme', misc.SetTheme.as_view(), name='set_theme'),
    
    path('weapon/', lists.WeaponListView.as_view(), name='weapon_list'),
    path('module/', lists.ModuleListView.as_view(), name='module_list'),
    path('effect/', lists.EffectListView.as_view(), name='effect_list'),
    path('overdrive/', lists.OverdriveListView.as_view(), name='overdrive_list'),
    path('enhancement/', lists.EnhancementListView.as_view(), name='enhancement_list'),
    path('armour/', lists.ArmourListView.as_view(), name='armour_list'),
    path('division/', lists.DivisionListView.as_view(), name='division_list'),
    path('arcana/', lists.ArcanaListView.as_view(), name='arcana_list'),
    path('crest/', lists.CrestListView.as_view(), name='crest_list'),
    path('archetype/', lists.ArchetypeListView.as_view(), name='archetype_list'),
    path('great_deed/', lists.GreatDeedListView.as_view(), name='great_deed_list'),
    path('skill/', lists.HeroicSkillListView.as_view(), name='skill_list'),
    path('vehicle/', lists.VehicleListView.as_view(), name='vehicle_list'),
    path('trauma/', lists.TraumaListView.as_view(), name='trauma_list'),
    path('mecha/', lists.MechaArmourListView.as_view(), name='mecha_list'),
    path('npc_capacity/', lists.NonPlayerCharacterCapacityListView.as_view(), name='npc_capacity_list'),
    
    path('weapon/<int:pk>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<int:pk>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<int:pk>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<int:pk>', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<int:pk>', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/<int:pk>', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<int:pk>', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<int:pk>', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<int:pk>', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('skill/<int:pk>', details.HeroicSkillDetailView.as_view(), name='skill_detail'),
    path('vehicle/<int:pk>', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<int:pk>', details.TraumaDetailView.as_view(), name='trauma_detail'),
    
    path('weapon/<slug:slug>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<slug:slug>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<slug:slug>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<slug:slug>', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<slug:slug>', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/classified', details.ArmourClassifiedView.as_view(), name='armour_unknown'),
    path('armour/<slug:slug>', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<slug:slug>', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<slug:slug>', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<slug:slug>', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('skill/<slug:slug>', details.HeroicSkillDetailView.as_view(), name='skill_detail'),
    path('archetype/<slug:slug>', details.ArchetypeDetailView.as_view(), name='archetype_detail'),
    path('crest/<slug:slug>', details.CrestDetailView.as_view(), name='crest_detail'),
    path('vehicle/<slug:slug>', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<slug:slug>', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('mecha/classified', details.MechaArmourClassifiedView.as_view(), name='mecha_unknown'),
    path('mecha/<slug:slug>', details.MechaArmourDetailView.as_view(), name='mecha_detail'),
    path('npc_capacity/<slug:slug>', details.NonPlayerCharacterCapacityDetailView.as_view(), name='npc_capacity_detail'),
    
    path('longbow_calculator/', calculators.LongbowCalculatorView.as_view(), name='longbow_calculator'),
    
    path('faq/v1', faq.QuestionV1ListView.as_view(), name='faqv1'),
    path('faq/v1.5', faq.QuestionV1Dot5ListView.as_view(), name='faqv1.5'),
    
    path('search/', searches.search, name='search'),
    
    path('print/weapon/', prints.WeaponPrintListView.as_view(), name='print_weapon'),
    path('print/module/', prints.ModulePrintListView.as_view(), name='print_module'),
    path('print/overdrive/', prints.OverdrivePrintListView.as_view(), name='print_overdrive'),
    path('print/enhancement/', prints.EnhancementPrintListView.as_view(), name='print_enhancement'),
    path('print/trauma/', prints.TraumaPrintListView.as_view(), name='print_trauma'),

]

knight_master_overview/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib.auth.decorators import login_required

from .views import account

urlpatterns = [
    path('camelot/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/', include('api.urls')),
    path('accounts/login/', account.JointLoginSignupView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
]

gm_urls = ([
    path('', include('gm.urls')),
], 'gm')


virtualtable_urls = ([
    path('', include('virtualtable.urls')),
], 'virtualtable')

urlpatterns += i18n_patterns(
    path('', include('gm.urls')),
    path('virtualtable/', include('virtualtable.urls')),
    path('users/', include('users.urls')),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

gm/views/calculators.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import Q, Min

from ..models.weaponry import Weapon, Reach

class LongbowCalculatorView(generic.View):
    def get(self, request):
        return render(request, 'gm/calculators/longbow.html', {
            "longbow": Weapon.objects.get(slug='fusil-longbow'),
        })
    

gm/views/details.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import Q, Min
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.character import Armour, Division, MajorArcana, GreatDeed, ArmourAbility, ArmourEvolution, ArmourOverdrive, DivisionOverdrive, Crest, Archetype, Trauma, MechaArmour, MechaArmourConfiguration, NonPlayerCharacterCapacity, NonPlayerCharacterType
from ..models.weaponry import Weapon, Effect, Module, Overdrive, Enhancement, HeroicSkill, EnhancementEffect, ModuleLevel, ModuleSlot, DivisionModule, DivisionWeapon, WeaponAttack, Vehicle, ModuleVehicle, MechaArmourActionCommon
from users.models import FavoriteWeapon, FavoriteEffect, FavoriteEnhancement, FavoriteArmour, FavoriteModule, FavoriteMechaArmour

class WeaponDetailView(generic.DetailView):
    model = Weapon
    template_name = 'gm/details/weapon.html'
    
    def get_object(self):
        weapon = super(WeaponDetailView, self).get_object()
        weapon.attacks_list = WeaponAttack.objects.filter(weapon=weapon.id).prefetch_related('effects', 'effects__effect').select_related('reach').order_by('position').all()
        weapon.enhancements_list = Enhancement.objects.filter(weapon=weapon.id).prefetch_related('effects', 'effects__effect').all()
        weapon.count_attacks = len(weapon.attacks_list)
        weapon.count_enhancements = len(weapon.enhancements_list)
        weapon.is_favorite = False
        if self.request.user.is_authenticated and len(FavoriteWeapon.objects.filter(user=self.request.user, weapon=weapon)):
            weapon.is_favorite = True
        return weapon


class EffectDetailView(generic.DetailView):
    model = Effect
    template_name = 'gm/details/effect.html'
    
    def get_object(self):
        effect = super(EffectDetailView, self).get_object()
        effect.weapons_list = Weapon.objects.filter(pk__in=effect.weaponattackeffects.values_list('weapon_attack__weapon__pk', flat=True)).order_by('rarity', 'name').all()
        effect.modules_list = (Module
            .objects
            .filter(
                pk__in=effect.moduleleveleffects.values_list('module_level__module__pk', flat=True)
            )
            .annotate(
                min_rarity=Min(
                    'levels__rarity__id',
                    filter=Q(levels__pk__in=effect.moduleleveleffects.values_list('module_level__pk', flat=True))
                ),
            )
            .select_related('category')
            .order_by('min_rarity', 'name')
            .all()
        )
        effect.enhancements_list = Enhancement.objects.filter(pk__in=effect.enhancements.values_list('enhancement__pk', flat=True)).all()
        effect.count_weapons = len(effect.weapons_list)
        effect.count_modules = len(effect.modules_list)
        effect.count_enhancements = len(effect.enhancements_list)
        effect.is_favorite = False
        if self.request.user.is_authenticated and len(FavoriteEffect.objects.filter(user=self.request.user, effect=effect)):
            effect.is_favorite = True
        return effect


class ModuleDetailView(generic.DetailView):
    model = Module
    template_name = 'gm/details/module.html'
    
    def get_object(self):
        module = super(ModuleDetailView, self).get_object()
        module.slots_list = ModuleSlot.objects.filter(module=module.id).all()
        module.levels_list = ModuleLevel.objects.filter(module=module.id).select_related('reach', 'activation', 'rarity').prefetch_related('effects', 'effects__effect', 'npcs', 'npcs__characteristics', 'npcs__characteristics__characteristic').all()
        module.vehicles_list = ModuleVehicle.objects.filter(module=module.id).select_related('vehicle').all()
        module.enhancements_list = Enhancement.objects.filter(modules=module.id).prefetch_related('effects', 'effects__effect').all()
        module.count_slots = len(module.slots_list)
        module.count_enhancements = len(module.enhancements_list)
        module.is_favorite = False
        if self.request.user.is_authenticated and len(FavoriteModule.objects.filter(user=self.request.user, module=module)):
            module.is_favorite = True
        return module


class OverdriveDetailView(generic.DetailView):
    model = Overdrive
    template_name = 'gm/details/overdrive.html'
    

class EnhancementDetailView(generic.DetailView):
    model = Enhancement
    template_name = 'gm/details/enhancement.html'
    
    def get_object(self):
        enhancement = super(EnhancementDetailView, self).get_object()
        enhancement.effects_list = EnhancementEffect.objects.filter(enhancement=enhancement.id).select_related('effect').all()
        enhancement.count_effects = len(enhancement.effects_list)
        enhancement.is_favorite = False
        if self.request.user.is_authenticated and len(FavoriteEnhancement.objects.filter(user=self.request.user, enhancement=enhancement)):
            enhancement.is_favorite = True
        return enhancement


class ArmourClassifiedView(generic.View):
    def get(self, request):
        return render(request, 'gm/details/armour_classified.html')

class ArmourDetailView(generic.DetailView):
    model = Armour
    template_name = 'gm/details/armour.html'
    
    def get_object(self):
        armour = super(ArmourDetailView, self).get_object()
        armour.overdrives_list = ArmourOverdrive.objects.filter(armour=armour.id).prefetch_related('characteristic').all()
        armour.evolutions_list = ArmourEvolution.objects.filter(armour=armour.id).all()
        armour.abilities_list = ArmourAbility.objects.filter(armour=armour.id).prefetch_related('variants', 'variants__reach', 'variants__npc', 'variants__npc__aspects', 'variants__npc__aspects__aspect').all()
        armour.is_favorite = False
        if self.request.user.is_authenticated and len(FavoriteArmour.objects.filter(user=self.request.user, armour=armour)):
            armour.is_favorite = True
        
        armour.is_allowed = True
        if armour.password is not None:
            if not self.request.user.is_authenticated:
                armour.is_allowed = False
            elif not self.request.user.game_master and armour not in self.request.user.unlocked_armours.all():
                armour.is_allowed = False
        
        return armour


class DivisionDetailView(generic.DetailView):
    model = Division
    template_name = 'gm/details/division.html'
    
    def get_object(self):
        division = super(DivisionDetailView, self).get_object()
        division.overdrives_list = DivisionOverdrive.objects.filter(division=division.id).prefetch_related('characteristic').all()
        division.modules_list = DivisionModule.objects.filter(division=division.id).select_related('module_level', 'module_level__module', 'forced_choice_effect').all()
        division.weapons_list = DivisionWeapon.objects.filter(division=division.id).select_related('weapon', 'weapon__category').all()
        return division
    

class ArcanaDetailView(generic.DetailView):
    model = MajorArcana
    template_name = 'gm/details/arcana.html'
    context_object_name = 'arcana'
    
    # def get_object(self):
    #     division = super(DivisionDetailView, self).get_object()
    #     division.overdrives_list = DivisionOverdrive.objects.filter(division=division.id).prefetch_related('characteristic').all()
    #     division.modules_list = DivisionModule.objects.filter(division=division.id).select_related('module_level', 'module_level__module', 'forced_choice_effect').all()
    #     division.weapons_list = DivisionWeapon.objects.filter(division=division.id).select_related('weapon', 'weapon__category').all()
    #     return division
    

class GreatDeedDetailView(generic.DetailView):
    model = GreatDeed
    template_name = 'gm/details/great_deed.html'
    context_object_name = 'great_deed'
    
class CrestDetailView(generic.DetailView):
    model = Crest
    template_name = 'gm/details/crest.html'
    context_object_name = 'crest'
    
class ArchetypeDetailView(generic.DetailView):
    model = Archetype
    template_name = 'gm/details/archetype.html'
    context_object_name = 'archetype'
    

class HeroicSkillDetailView(generic.DetailView):
    model = HeroicSkill
    template_name = 'gm/details/skill.html'
    context_object_name = 'skill'
    

class VehicleDetailView(generic.DetailView):
    model = Vehicle
    template_name = 'gm/details/vehicle.html'
    context_object_name = 'vehicle'

class TraumaDetailView(LoginRequiredMixin, generic.DetailView):
    model = Trauma
    template_name = 'gm/details/trauma.html'
    
    def get_object(self):
        trauma = super(TraumaDetailView, self).get_object()
        
        trauma.is_allowed = True
        if trauma.password is not None:
            if not self.request.user.is_authenticated:
                trauma.is_allowed = False
            elif not self.request.user.game_master and trauma not in self.request.user.unlocked_traumas.all():
                trauma.is_allowed = False
        
        return trauma

class MechaArmourClassifiedView(generic.View):
    def get(self, request):
        return render(request, 'gm/details/mecha_classified.html')
        
class MechaArmourDetailView(LoginRequiredMixin, generic.DetailView):
    model = MechaArmour
    template_name = 'gm/details/mecha.html'
    context_object_name = 'mecha'
    
    def get_object(self):
        mecha = super(MechaArmourDetailView, self).get_object()
        mecha.configurations_list = MechaArmourConfiguration.objects.filter(mecha=mecha.id).prefetch_related('actions', 'actions__reach').all()
        mecha.actions_list = MechaArmourActionCommon.objects.filter(mecha=mecha.id).prefetch_related('reach').all()
        mecha.is_favorite = False

gm/templates/gm/details/archetype.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Archétype" %} {{ archetype.name }} - {% endblock %}

{% block content %}
    <a href="{% url 'gm:archetype_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des archétypes" %}</a>
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{{ archetype.name }}</h1>
    </div>
    
    <div class="card-deck">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans 'Description' %}
                </h5>
            </div>
            <div class="card-body text-justify">
                {{ archetype.description|linebreaks }}
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans 'Bonus carac.' %}
                </h5>
            </div>
            <div class="card-body text-justify">
                {% if archetype.characteristic_bonus_1 or archetype.characteristic_bonus_2 or archetype.characteristic_bonus_3 %}
                    <ul class="m-0">
                        <li>{{ archetype.characteristic_bonus_1.name }}</li>
                        <li>
                            {{ archetype.characteristic_bonus_2.name }}
                            {% if archetype.characteristic_bonus_3 %}
                                {% blocktrans trimmed with charac_name=archetype.characteristic_bonus_3.name %}
                                    OU {{ charac_name }}
                                {% endblocktrans %}
                            {% endif %}
                        </li>
                    </ul>
                {% else %}
                    {% trans 'Deux différentes au choix, à définir' %}
                {% endif %}
            </div>
        </div>
    </div>
    
    {% if archetype.faq_text or archetype.questions.all %}
        {% include 'gm/misc/faq_text.html' with faq_text=archetype.faq_text questions=archetype.questions.all %}
    {% endif %}
{% endblock %}

gm/templates/gm/details/armour_classified.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}
{% load gm_extras %}

{% block title %}{% trans "Armure confidentielle" %} - {% endblock %}

{% block content %}
    <a href="{% url 'gm:armour_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des armures" %}</a>
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{% trans "[CONFIDENTIEL]"%}</h1>
        <h4 class="text-center">
            <span class="badge badge-pill badge-primary">{% trans 'PA' %} ?</span>
            <span class="badge badge-pill badge-success">{% trans 'PE' %} ?</span>
            <span class="badge badge-pill badge-danger">{% trans 'CdF' %} ?</span>
            <span class="badge badge-pill badge-warning">{% trans 'Gen.' %} ?</span>
        </h4>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h5 class="font-weight-bold font-italic mb-0">
                {% trans "Accréditations limitées" %}
            </h5>
        </div>
        <div class="card-body text-justify">
            {% blocktrans trimmed %}
                Vous n'avez pas les accréditations nécessaires pour visualiser cette armure.
                Vous pouvez demander le code d'activation à votre MJ.
                Une fois le code en votre possession, allez dans votre profil et dans la section "Accréditations",
                collez le code fourni. Il vous débloquera l'accès à l'armure, qui sera dans la liste des armures.
            {% endblocktrans %}
        </div>
    </div>
{% endblock %}

gm/templates/gm/details/division.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Section" %} {{ division.name }} - {% endblock %}

{% block content %}
    <a href="{% url 'gm:division_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des sections" %}</a>
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{{ division.name}}</h1>
        <blockquote class="blockquote font-italic text-center text-muted">
            <p>{{ division.motto }}</p>
        </blockquote>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h5 class="font-weight-bold font-italic mb-0">{% trans "Description" %}</h5>
        </div>
        <div class="card-body markdown-format text-justify">
            {{ division.description|safe_markdown }}
        </div>
    </div>
    <div class="card-deck mb-sm-3">
        {% if division.weapons_list %}
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold font-italic mb-0">
                        {% blocktrans trimmed count counter=division.weapons_list|length %}
                            Arme offerte
                        {% plural %}
                            Armes offertes
                        {% endblocktrans %}
                    </h5>
                </div>
                <div class="card-body">
                    <ul>
                        {% for weapon_division in division.weapons_list %}
                            <li><a href="{% url 'gm:weapon_detail' weapon_division.weapon.slug %}">[{{ weapon_division.weapon.category.name }}] {{ weapon_division.weapon.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        {% if division.overdrives_list %}
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold font-italic mb-0">
                        {% blocktrans trimmed count counter=division.overdrives_list|length %}
                            Overdrive offert
                        {% plural %}
                            Overdrives offerts
                        {% endblocktrans %}
                    </h5>
                </div>
                <div class="card-body">
                    <ul>
                        {% for overdrive in division.overdrives_list %}
                            {% with od=overdrive.characteristic.name|slugify|add:'-1' %}
                                <li><a href="{% url 'gm:overdrive_detail' od %}">{{ overdrive.characteristic.name }}</a></li>
                            {% endwith%}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        {% if division.modules_list %}
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold font-italic mb-0">
                        {% blocktrans trimmed count counter=division.modules_list|length %}
                            Module offert
                        {% plural %}
                            Modules offerts
                        {% endblocktrans %}
                    </h5>
                </div>
                <div class="card-body">
                    <ul>
                        {% for module_division in division.modules_list %}
                            <li>
                                <a href="{% url 'gm:module_detail' module_division.module_level.module.slug %}">
                                    {{ module_division.module_level }}
                                    {% if module_division.forced_choice_effect %}
                                        ({{ module_division.forced_choice_effect }})
                                    {% endif %}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="card">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans 'Aspect' %}
                </h5>
            </div>
            <div class="card-body">
                {% blocktrans trimmed with aspect=division.aspect_bonus.name %}
                    Augmente 1 point dans l'Aspect <em>{{ aspect }}</em> et 1 point dans chaque caractéristique associée à ce dernier :
                {% endblocktrans %}
                <ul>
                    {% for characteristic in division.aspect_bonus.characteristics.all %}
                        <li>
                            <em>{{ characteristic.name }}</em>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    
    <div class="card mb-3">
        <div class="card-header">
            <h5 class="font-weight-bold font-italic mb-0">
                {% trans 'Inconvénient' %} - {{ division.disadvantage_name }}
            </h5>
        </div>
        <div class="card-body">
            <div class="text-justify markdown-format">{{ division.disadvantage|safe_markdown }}</div>
        </div>
    </div>
    
    {% if division.faq_text or division.questions.all %}
        {% include 'gm/misc/faq_text.html' with faq_text=division.faq_text questions=division.questions.all %}
    {% endif %}
{% endblock %}

gm/templates/gm/details/trauma.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Trauma" %} {{ trauma.name }} - {% endblock %}

{% block content %}
    {% if user.is_authenticated and user.game_master %}
        <a href="{% url 'gm:trauma_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des traumas" %}</a>
    {% else %}
        <a href="{% url 'gm:index' %}">{% trans "Accueil" %}</a>
    {% endif %}
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{{ trauma.name }}</h1>
        {% if trauma.is_allowed %}
            <h4 class="text-center">
                <span class="badge badge-pill badge-secondary">{{ trauma.category.name }}</span>
                <span class="badge badge-pill badge-secondary">+{{ trauma.category.hop_recovered }} {% trans "PES" %}</span>
                {% if trauma.die_value %}
                    <span class="badge badge-pill badge-secondary">D6 = {{ trauma.die_value }}</span>
                {% endif %}
            </h4>
            {% if trauma.password and user.game_master %}
                <p>{% trans "Mot de passe pour accéder à ce trauma :" %} <span class="font-italic">{{ trauma.password }}</span></p>
            {% endif %}
        {% endif %}
    </div>
    {% if not trauma.is_allowed %}
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans "Pleine santé" %}
                </h5>
            </div>
            <div class="card-body text-justify">
                {% blocktrans trimmed %}
                    Il semblerait que vous n'ayez aucune séquelle. Si vous deviez subir ce trauma, demandez
                    le code d'activation à votre MJ, qui doit l'avoir visible sur cette même page.
                    Une fois le code en votre possession, allez dans votre profil et dans la section "Accréditations",
                    collez le code fourni. Il vous donnera accès au descriptif de ce trauma.
                {% endblocktrans %}
            </div>
        </div>
    {% else %}
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans 'Description' %}
                </h5>
            </div>
            <div class="card-body text-justify">
                <div class="markdown-format">
                    {{ trauma.description|safe_markdown }}
                </div>
            </div>
        </div>
        
        {% if trauma.faq_text or trauma.questions.all %}
            {% include 'gm/misc/faq_text.html' with faq_text=trauma.faq_text questions=trauma.questions.all %}
        {% endif %}
    {% endif %}
{% endblock %}

gm/templates/gm/details/vehicle.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Véhicule" %} {{ vehicle.name }} - {% endblock %}

{% block content %}
    <a href="{% url 'gm:vehicle_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des véhicules" %}</a>
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{{ vehicle.name }}</h1>
    </div>
    {% include 'gm/misc/vehicle_detail.html' with vehicle=vehicle only %}
    
    {% if vehicle.faq_text or vehicle.questions.all %}
        {% include 'gm/misc/faq_text.html' with faq_text=vehicle.faq_text questions=vehicle.questions.all %}
    {% endif %}
{% endblock %}