gm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import misc, calculators, searches, lists, details, prints, faq

app_name = 'gm'
urlpatterns = [
    path('', misc.IndexView.as_view(), name='index'),
    path('about/', misc.AboutView.as_view(), name='about'),
    path('ai_generator/', cache_page(0)(misc.generateAI), name='ai_generator'),
    path('ai_generator/<codename>/', misc.generateAI, name='ai_informations'),
    path('ajax/autocomplete.json', misc.AutocompleteView.as_view(), name='autocomplete'),
    path('ajax/theme', misc.SetTheme.as_view(), name='set_theme'),
    
    path('weapon/', lists.WeaponListView.as_view(), name='weapon_list'),
    path('module/', lists.ModuleListView.as_view(), name='module_list'),
    path('effect/', lists.EffectListView.as_view(), name='effect_list'),
    path('overdrive/', lists.OverdriveListView.as_view(), name='overdrive_list'),
    path('enhancement/', lists.EnhancementListView.as_view(), name='enhancement_list'),
    path('armour/', lists.ArmourListView.as_view(), name='armour_list'),
    path('division/', lists.DivisionListView.as_view(), name='division_list'),
    path('arcana/', lists.ArcanaListView.as_view(), name='arcana_list'),
    path('crest/', lists.CrestListView.as_view(), name='crest_list'),
    path('archetype/', lists.ArchetypeListView.as_view(), name='archetype_list'),
    path('great_deed/', lists.GreatDeedListView.as_view(), name='great_deed_list'),
    path('skill/', lists.HeroicSkillListView.as_view(), name='skill_list'),
    path('vehicle/', lists.VehicleListView.as_view(), name='vehicle_list'),
    path('trauma/', lists.TraumaListView.as_view(), name='trauma_list'),
    path('mecha/', lists.MechaArmourListView.as_view(), name='mecha_list'),
    path('npc_capacity/', lists.NonPlayerCharacterCapacityListView.as_view(), name='npc_capacity_list'),
    
    path('weapon/<int:pk>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<int:pk>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<int:pk>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<int:pk>', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<int:pk>', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/<int:pk>', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<int:pk>', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<int:pk>', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<int:pk>', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('skill/<int:pk>', details.HeroicSkillDetailView.as_view(), name='skill_detail'),
    path('vehicle/<int:pk>', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<int:pk>', details.TraumaDetailView.as_view(), name='trauma_detail'),
    
    path('weapon/<slug:slug>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<slug:slug>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<slug:slug>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<slug:slug>', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<slug:slug>', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/classified', details.ArmourClassifiedView.as_view(), name='armour_unknown'),
    path('armour/<slug:slug>', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<slug:slug>', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<slug:slug>', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<slug:slug>', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('skill/<slug:slug>', details.HeroicSkillDetailView.as_view(), name='skill_detail'),
    path('archetype/<slug:slug>', details.ArchetypeDetailView.as_view(), name='archetype_detail'),
    path('crest/<slug:slug>', details.CrestDetailView.as_view(), name='crest_detail'),
    path('vehicle/<slug:slug>', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<slug:slug>', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('mecha/classified', details.MechaArmourClassifiedView.as_view(), name='mecha_unknown'),
    path('mecha/<slug:slug>', details.MechaArmourDetailView.as_view(), name='mecha_detail'),
    path('npc_capacity/<slug:slug>', details.NonPlayerCharacterCapacityDetailView.as_view(), name='npc_capacity_detail'),
    
    path('longbow_calculator/', calculators.LongbowCalculatorView.as_view(), name='longbow_calculator'),
    
    path('faq/v1', faq.QuestionV1ListView.as_view(), name='faqv1'),
    path('faq/v1.5', faq.QuestionV1Dot5ListView.as_view(), name='faqv1.5'),
    
    path('search/', searches.search, name='search'),
    
    path('print/weapon/', prints.WeaponPrintListView.as_view(), name='print_weapon'),
    path('print/module/', prints.ModulePrintListView.as_view(), name='print_module'),
    path('print/overdrive/', prints.OverdrivePrintListView.as_view(), name='print_overdrive'),
    path('print/enhancement/', prints.EnhancementPrintListView.as_view(), name='print_enhancement'),
    path('print/trauma/', prints.TraumaPrintListView.as_view(), name='print_trauma'),

]

knight_master_overview/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib.auth.decorators import login_required

from .views import account

urlpatterns = [
    path('camelot/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/', include('api.urls')),
    path('accounts/login/', account.JointLoginSignupView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
]

gm_urls = ([
    path('', include('gm.urls')),
], 'gm')


virtualtable_urls = ([
    path('', include('virtualtable.urls')),
], 'virtualtable')

urlpatterns += i18n_patterns(
    path('', include('gm.urls')),
    path('virtualtable/', include('virtualtable.urls')),
    path('users/', include('users.urls')),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

users/urls.py
from django.urls import include, path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'users'
urlpatterns = [
    path('favorites/', cache_page(0)(views.ListFavoritesView.as_view()), name='fav_list'),
    
    # Profile part
    path('profile/', cache_page(0)(views.ProfileView.as_view()), name='profile'),
    path('del_user/', cache_page(0)(views.DeleteUserView.as_view()), name='del_user'),
    path('password/', cache_page(0)(views.PasswordChangeView.as_view()), name='change_password'),
    
    
    # Fav from detail part
    path('fav_add/', cache_page(0)(views.AddToFavView.as_view()), name='fav_add'),
    path('fav_del/', cache_page(0)(views.DelFromFavView.as_view()), name='fav_del'),
    
    # Item management part
    path('fav_copy_item/', cache_page(0)(views.MoveFavItemView.as_view()), name='fav_copy_item'),
    path('fav_del_item/', cache_page(0)(views.DelFavItemView.as_view()), name='fav_del_item'),
    path('fav_edit_item/', cache_page(0)(views.EditItemToFavView.as_view()), name='fav_edit_item'),
    path('fav_move_item/', cache_page(0)(views.MoveFavItemView.as_view()), name='fav_move_item'),
    
    # List management part
    path('fav_add_list/', cache_page(0)(views.AddFavListView.as_view()), name='fav_add_list'),
    path('fav_del_list/', cache_page(0)(views.DelFavListView.as_view()), name='fav_del_list'),
    path('fav_edit_list/', cache_page(0)(views.EditFavListView.as_view()), name='fav_edit_list'),
    path('fav_order_list/', cache_page(0)(views.OrderFavListView.as_view()), name='fav_order_list'),
]

virtualtable/urls.py
from django.urls import include, path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'virtualtable'
urlpatterns = [
    path('create/', cache_page(0)(views.CreateTableView.as_view()), name='vt_create'),
    path('list/', cache_page(0)(views.ListTableView.as_view()), name='vt_list'),
    path('detail/<int:pk>', cache_page(0)(views.DetailTableView.as_view()), name='vt_detail'),
    path('delete/<int:pk>', cache_page(0)(views.DeleteTableView.as_view()), name='vt_delete'),
    path('update/<int:pk>', cache_page(0)(views.UpdateTableView.as_view()), name='vt_update'),
    path('help/', cache_page(0)(views.HelpTableView.as_view()), name='vt_help'),
    
    path('test/', cache_page(0)(views.TestView.as_view()), name='vt_test'),
    
    path('join/<str:invitation_token>/', cache_page(0)(views.PlayerJoinTableView.as_view()), name='join'),
]

gm/models/faq.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey

from martor.models import MartorField
from gettext import gettext
import bleach
from markdown import markdown

class Category(MPTTModel):
    name = models.CharField("nom", max_length=128)
    css_classes = models.CharField("classes CSS", max_length=256, blank=True)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        verbose_name="Catégorie parent",
        related_name="children",
        blank=True,
        null=True
    )
    
    class MPTTMeta:
        order_insertion_by = ['name']
    
    def __str__(self):
        return self.name
    

class Question(models.Model):
    question = models.CharField("question", max_length=512)
    answer = MartorField("réponse", blank=True, null=True)
    gm = models.BooleanField('filtre MJ', blank=True, default=False)
    v1 = models.BooleanField('compatible v1', blank=True, default=True)
    v1_5 = models.BooleanField('compatible v1.5', blank=True, default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = TreeForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="catégorie",
        related_name="questions"
    )
    
    def __str__(self):
        return self.question
        
    def question_text_only(self):
        return bleach.clean(markdown(self.question), tags=[], strip=True)
    
    def answer_text_only(self):
        if self.answer:
            return bleach.clean(markdown(self.answer), tags=[], strip=True)
        else:
            return ''
    

gm/views/calculators.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import Q, Min

from ..models.weaponry import Weapon, Reach

class LongbowCalculatorView(generic.View):
    def get(self, request):
        return render(request, 'gm/calculators/longbow.html', {
            "longbow": Weapon.objects.get(slug='fusil-longbow'),
        })
    

gm/views/faq.py
from django.views import generic
from django.db.models import Q, Count, Prefetch
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.faq import Category, Question

class QuestionV1ListView(generic.ListView):
    template_name = 'gm/faq/list.html'
    context_object_name = 'faq'
    
    def get_context_data(self, **kwargs):
        context = super(QuestionV1ListView, self).get_context_data(**kwargs)
        
        prefetch = Prefetch(
            'questions',
            queryset=Question.objects.filter(v1=True, gm=False).order_by('-created')
        )
        
        if self.request.user.is_authenticated and self.request.user.game_master:
            prefetch = Prefetch(
                'questions',
                queryset=Question.objects.filter(v1=True).order_by('-created')
            )
        
        categories = Category.objects.prefetch_related(prefetch).all()
        displayed_category = []
        index_category = {}
        
        for category in categories:
            index_category[category.id] = len(displayed_category)
            displayed_category.append((category, category.is_leaf_node() and len(category.questions.all()) > 0))
            
            if category.is_leaf_node():
                if len(category.questions.all()) > 0:
                    for ancestor in category.get_ancestors():
                        displayed_category[index_category[ancestor.id]] = (ancestor, True)
        
        context['displayed_categories'] = displayed_category
        
        return context
        
    def get_queryset(self):
        """Return list of weapon."""
        return (Question
            .objects
            .filter(
                v1=True
            )
            .order_by('category', '-created'))

class QuestionV1Dot5ListView(generic.ListView):
    template_name = 'gm/faq/list.html'
    context_object_name = 'faq'
    
    def get_context_data(self, **kwargs):
        context = super(QuestionV1Dot5ListView, self).get_context_data(**kwargs)
        
        prefetch = Prefetch(
            'questions',
            queryset=Question.objects.filter(v1_5=True, gm=False).order_by('-created')
        )
        
        if self.request.user.is_authenticated and self.request.user.game_master:
            prefetch = Prefetch(
                'questions',
                queryset=Question.objects.filter(v1_5=True).order_by('-created')
            )
        
        categories = Category.objects.prefetch_related(prefetch).all()
        displayed_category = []
        index_category = {}
        
        for category in categories:
            index_category[category.id] = len(displayed_category)
            displayed_category.append((category, category.is_leaf_node() and len(category.questions.all()) > 0))
            
            if category.is_leaf_node():
                if len(category.questions.all()) > 0:
                    for ancestor in category.get_ancestors():
                        displayed_category[index_category[ancestor.id]] = (ancestor, True)
        
        context['displayed_categories'] = displayed_category
        
        return context
        
    def get_queryset(self):
        """Return list of weapon."""
        return (Question
            .objects
            .filter(
                v1_5=True
            )
            .order_by('category', '-created'))

gm/views/prints.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import Min, Max, Count

from ..models.weaponry import Weapon, Module, Overdrive, Enhancement
from ..models.character import Trauma

class WeaponPrintListView(generic.ListView):
    template_name = 'gm/prints/weapon.html'
    context_object_name = 'weapon_list'

    def get_queryset(self):
        """Return list of weapon."""
        return Weapon.objects.filter(player_enabled=True).order_by('category', 'rarity', 'name').select_related('rarity', 'category').prefetch_related('attacks', 'attacks__reach', 'attacks__effects', 'attacks__effects__effect', 'enhancements')


class ModulePrintListView(generic.ListView):
    template_name = 'gm/prints/module.html'
    context_object_name = 'module_list'

    def get_queryset(self):
        """Return list of module."""
        return Module.objects.annotate(min_rarity=Min('levels__rarity__id'), max_level=Max('levels__level')).prefetch_related('levels', 'levels__effects', 'levels__effects__effect', 'levels__rarity', 'levels__activation', 'levels__reach').select_related('category').order_by('category', 'min_rarity', 'name')


class OverdrivePrintListView(generic.ListView):
    template_name = 'gm/prints/overdrive.html'
    context_object_name = 'overdrive_list'

    def get_queryset(self):
        """Return list of overdrive."""
        return Overdrive.objects.order_by('characteristic__aspect__id', 'characteristic__id', 'level').select_related('characteristic', 'characteristic__aspect', 'rarity')
    

class EnhancementPrintListView(generic.ListView):
    template_name = 'gm/prints/enhancement.html'
    context_object_name = 'enhancement_list'

    def get_queryset(self):
        """Return list of enhancement."""
        return Enhancement.objects.order_by('group', 'name').select_related('category')

class TraumaPrintListView(generic.ListView):
    template_name = 'gm/prints/trauma.html'
    context_object_name = 'trauma_list'

    def get_queryset(self):
        """Return list of traumas."""
        return (Trauma
            .objects
            .select_related('category')
            .order_by('category__hop_recovered', 'die_value'))

    

gm/templates/gm/base.html
{% load static %}
{% load i18n %}
{% load gm_extras %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}{{ KNIGHTOOLS_SITE_NAME }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% get_themed 'gm/css/bootstrap.$THEME$min.css' user request.session append=True append_str='.' as bootstrap_theme %}
    {% get_themed '$THEME$' user request.session only_name=True as bootstrap_theme_name %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static bootstrap_theme %}" />
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'gm/css/jquery-ui-1.12.1.min.css' %}" />
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'gm/css/jquery-ui-1.12.1.structure.min.css' %}" />
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'gm/css/style.css' %}" />
    {% get_themed 'gm/css/style.$THEME$css' user request.session append=True append_str='.' as knightools_style %}
    {% if knightools_style != 'gm/css/style.css' %}
        <link rel="stylesheet" type="text/css" media="all" href="{% static knightools_style %}" />
    {% endif %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'gm/css/flag-icon.css' %}" />
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'gm/css/all.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock css %}
    <link rel="icon" href="{% static 'gm/img/favicon.jpg' %}">
    
    <script type="text/javascript" src="{% static 'gm/js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'gm/js/jquery-ui-1.12.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'gm/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'gm/js/bootstrap.js' %}"></script>
    {% block js %}
    {% endblock js %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="{% url 'gm:index' %}" title="{{ KNIGHTOOLS_SITE_DESC }}">{{ KNIGHTOOLS_SITE_NAME }} {% if KNIGHTOOLS_SITE_BETA %}<sup><span class="badge badge-light"><small>&beta;</small></span></sup>{% endif %}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'gm:index' %}" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Accès rapide" %}</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="{% url 'gm:index' %}">{% trans "Accueil" %}</a>
                            <div class="dropdown-divider"></div>
                            <h6 class="dropdown-header">{% trans "Arsenal" %}</h6>
                            <a class="dropdown-item" href="{% url 'gm:weapon_list' %}">{% trans "Armes" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:module_list' %}">{% trans "Modules" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:enhancement_list' %}">{% trans "Améliorations" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:overdrive_list' %}">{% trans "Overdrives" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:effect_list' %}">{% trans "Effets" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:skill_list' %}">{% trans "Capacités héroïques" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:vehicle_list' %}">{% trans "Véhicules" %}</a>
                            <div class="dropdown-divider"></div>
                            <h6 class="dropdown-header">{% trans "Création de personnages" %}</h6>
                            <a class="dropdown-item" href="{% url 'gm:archetype_list' %}">{% trans "Archétypes" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:arcana_list' %}">{% trans "Arcanes majeures" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:great_deed_list' %}">{% trans "Hauts-faits" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:crest_list' %}">{% trans "Blasons" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:armour_list' %}">{% trans "Armures" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:division_list' %}">{% trans "Sections" %}</a>
                            <a class="dropdown-item" href="{% url 'gm:ai_generator' %}">{% trans "Générateur d'IA" %}</a>
                            {% if user.access_to_restricted_area %}
                                <div class="dropdown-divider"></div>
                                <h6 class="dropdown-header">
                                    {% if user.game_master %}
                                        {% trans "Accès MJ" %}
                                    {% else %}
                                        {% trans "Accès restreint" %}
                                    {% endif %}
                                </h6>
                                {% if user.is_trauma_visible %}
                                    <a class="dropdown-item" href="{% url 'gm:trauma_list' %}">{% trans "Traumas" %}</a>
                                {% endif %}
                                {% if user.is_mecha_visible %}
                                    <a class="dropdown-item" href="{% url 'gm:mecha_list' %}">{% trans "Mecha-armures" %}</a>
                                {% endif %}
                                {% if user.is_npc_capacity_visible %}
                                    <a class="dropdown-item" href="{% url 'gm:npc_capacity_list' %}">{% trans "Capacités PNJ" %}</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gm:about' %}">{% trans "À propos" %}</a>
                    </li>
                    <li class="nav-item dropdown d-none">
                        <a class="nav-link dropdown-toggle"href="{% url 'gm:index' %}" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Langue" %}</a>
                        {% get_available_languages as languages %}
                        <div class="dropdown-menu" aria-labelledby="dropdown02">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <a class="dropdown-item {% if language.code == LANGUAGE_CODE %} active{% endif %}" href="#" onclick="knightools.set_language('{{ language.code }}')" data-lang="{{ language.code }}"><span class="flag-icon flag-icon-{{ language.code }} mr-1"></span>{{ language.name }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"href="{% url 'gm:index' %}" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Thème" %}</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown02">
                            <a class="dropdown-item {% if bootstrap_theme_name == 'anathema' %}active{% endif %}" href="#" data-theme="anathema">Anathème</a>
                            <a class="dropdown-item {% if bootstrap_theme_name == 'graal' %}active{% endif %}" href="#" data-theme="graal">Graal</a>
                        </div>
                    </li>
                </ul>
                <form class="d-none" action="{% url 'set_language' %}" id="setlang" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <input name="language" type="hidden" value="{{ get_current_language }}">
                </form>
                <form class="d-none" action="{% url 'gm:set_theme' %}" id="set-theme" method="post"></form>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                                <h6 class="dropdown-header">{% trans "Compte" %}</h6>
                                <a class="dropdown-item" href="{% url 'users:fav_list' %}">{% trans "Favoris" %}</a>
                                <a class="dropdown-item" href="{% url 'virtualtable:vt_list' %}">{% trans "Tables" %}</a>
                                <a class="dropdown-item d-none" href="#todo">{% trans "Personnages (TODO)" %}</a>
                                <a class="dropdown-item" href="{% url 'users:profile' %}">{% trans "Profil" %}</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Déconnexion" %}</a>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}?next={{request.path}}">{% trans "Connexion / S'inscrire" %}</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav d-none {% block display_printer %}{% endblock display_printer %}">
                    <li class="nav-item">
                        <a class="nav-link" href="{% block printer %}{% endblock %}"><i class="fas fa-print"> {% trans "Version imprimable" %}</i></a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-md-0" action="{% url 'gm:search' %}" method="get">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1"><i class="fa fa-search"></i></span>
                        </div>
                        <input type="text" id="global-search" class="form-control" placeholder="{% trans 'Recherche' %}" aria-label="{% trans 'Recherche' %}" name="s">
                    </div>
                </form>
            </div>
        </nav>
        {% block warning %}
        {% endblock %}
    </header>
    
    <main class="container">
        {% block content %}
        {% endblock %}
        
        <div class="row">
            <div class="col-12 mt-2"></div><!-- used to avoid the bottom page to be stuck without space -->
        </div>
        <script src="{% static 'gm/js/knightools.js' %}"></script>
    </main>
</body>
</html>